Predicting next word with RNN

In [ ]:
import numpy as np
import tensorflow as tf
import keras
from keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from keras.utils import to_categorical

In [ ]:
sentences=[
    "I Love machine learning",
    "Machine learning is amazing",
    "Deep learning is a subset of machine learning",
    "I Like travelling around world",
    "AI can perform many tasks",
    "I enjoy learning new skills"
]

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
tokenizer.word_index

{'learning': 1,
 'i': 2,
 'machine': 3,
 'is': 4,
 'love': 5,
 'amazing': 6,
 'deep': 7,
 'a': 8,
 'subset': 9,
 'of': 10,
 'like': 11,
 'travelling': 12,
 'around': 13,
 'world': 14,
 'ai': 15,
 'can': 16,
 'perform': 17,
 'many': 18,
 'tasks': 19,
 'enjoy': 20,
 'new': 21,
 'skills': 22}

In [ ]:
total_words=len(tokenizer.word_index)+1
total_words

23

In [ ]:
input_sequences=[]
for i in sentences:
    token_list=tokenizer.texts_to_sequences([i])[0]
    for j in range(1,len(token_list)):
      n_gram_sequence=token_list[:j+1]
      input_sequences.append(n_gram_sequence)
input_sequences

[[2, 5],
 [2, 5, 3],
 [2, 5, 3, 1],
 [3, 1],
 [3, 1, 4],
 [3, 1, 4, 6],
 [7, 1],
 [7, 1, 4],
 [7, 1, 4, 8],
 [7, 1, 4, 8, 9],
 [7, 1, 4, 8, 9, 10],
 [7, 1, 4, 8, 9, 10, 3],
 [7, 1, 4, 8, 9, 10, 3, 1],
 [2, 11],
 [2, 11, 12],
 [2, 11, 12, 13],
 [2, 11, 12, 13, 14],
 [15, 16],
 [15, 16, 17],
 [15, 16, 17, 18],
 [15, 16, 17, 18, 19],
 [2, 20],
 [2, 20, 1],
 [2, 20, 1, 21],
 [2, 20, 1, 21, 22]]

In [ ]:
max_sequence_len=max([len(x) for x in input_sequences])
print(max_sequence_len)


8


In [ ]:
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))
input_sequences

array([[ 0,  0,  0,  0,  0,  0,  2,  5],
       [ 0,  0,  0,  0,  0,  2,  5,  3],
       [ 0,  0,  0,  0,  2,  5,  3,  1],
       [ 0,  0,  0,  0,  0,  0,  3,  1],
       [ 0,  0,  0,  0,  0,  3,  1,  4],
       [ 0,  0,  0,  0,  3,  1,  4,  6],
       [ 0,  0,  0,  0,  0,  0,  7,  1],
       [ 0,  0,  0,  0,  0,  7,  1,  4],
       [ 0,  0,  0,  0,  7,  1,  4,  8],
       [ 0,  0,  0,  7,  1,  4,  8,  9],
       [ 0,  0,  7,  1,  4,  8,  9, 10],
       [ 0,  7,  1,  4,  8,  9, 10,  3],
       [ 7,  1,  4,  8,  9, 10,  3,  1],
       [ 0,  0,  0,  0,  0,  0,  2, 11],
       [ 0,  0,  0,  0,  0,  2, 11, 12],
       [ 0,  0,  0,  0,  2, 11, 12, 13],
       [ 0,  0,  0,  2, 11, 12, 13, 14],
       [ 0,  0,  0,  0,  0,  0, 15, 16],
       [ 0,  0,  0,  0,  0, 15, 16, 17],
       [ 0,  0,  0,  0, 15, 16, 17, 18],
       [ 0,  0,  0, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0,  0,  0,  2, 20],
       [ 0,  0,  0,  0,  0,  2, 20,  1],
       [ 0,  0,  0,  0,  2, 20,  1, 21],
       [ 0,  0, 

In [ ]:
input = input_sequences[:, :-1]
print(input[4])
output = input_sequences[:, -1]
print(output[4])

[0 0 0 0 0 3 1]
4


In [ ]:
output_c=to_categorical(output,num_classes=total_words)
output_c[4]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [ ]:
import keras.layers as layers
RNN=keras.Sequential([
    layers.Embedding(total_words,100,input_length=max_sequence_len-1),
    layers.SimpleRNN(150),
    layers.Dense(total_words,activation='softmax')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
RNN.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
RNN.fit(input,output_c,epochs=100,verbose=1)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.0000e+00 - loss: 3.1471
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.2800 - loss: 3.0582
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.2000 - loss: 2.9710
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.2000 - loss: 2.8826
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.2000 - loss: 2.7958
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2000 - loss: 2.7215
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.2000 - loss: 2.6668
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.2000 - loss: 2.6114
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.2400 - loss: 2.5434
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.2400 - loss: 2.4754
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.2800 - loss: 2.4167
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4400 - 

In [ ]:
seed_text=__builtins__.input("enter the text:")
token_list=tokenizer.texts_to_sequences([seed_text])[0]
token_list=pad_sequences([token_list],maxlen=max_sequence_len-1,padding='pre')
predicted=RNN.predict(token_list)
predicted

enter the text:I Love
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step


array([[1.93022657e-04, 1.51278265e-02, 2.09371312e-04, 9.33583617e-01,
        1.37607014e-04, 1.65787688e-03, 2.49126140e-04, 1.66736820e-04,
        1.13920146e-03, 3.57960205e-04, 7.43825876e-05, 2.16575433e-03,
        3.97074707e-02, 5.32907958e-04, 3.62276623e-04, 1.01636469e-04,
        3.03234032e-04, 4.10451728e-04, 8.66209593e-05, 3.15886864e-04,
        2.82001845e-03, 2.91059823e-05, 2.68000760e-04]], dtype=float32)

In [ ]:
predicted=np.argmax(predicted,axis=1)
print(predicted)


[3]


In [ ]:
predicted_word=""
for word,index in tokenizer.word_index.items():
  if index == predicted:
    predicted_word=word
    break
print(f"The next word is:{predicted_word}")

The next word is:machine
